#!/bin/bash
steamos-readonly disable
pacman -U /home/deck/Android_Waydroid/pacman/cage-0.2.0-3-x86_64.pkg.tar.zst  /home/deck/Android_Waydroid/pacman/wlroots0.18-0.18.2-1-x86_64.pkg.tar.zst  /home/deck/Android_Waydroid/pacman/wlr-randr-0.5.0-1-x86_64.pkg.tar.zst --noconfirm
steamos-readonly enable
